### ISSUE TITLE
DNS resolution was failing - urllib3 throwing Connecting errors randomly

### ISSUE THREAD

**Issue by cjustinhall** [llevar/flickr_to_google_photos_migration#2]
Adding this for others who might be facing the same problem. I was getting DNS issues resolving to api.flickr.com. It was manifesting itself in urllib3 throwing Connecting errors randomly, usually after 80 images were pulled in the build_migration_photos_list.py script.

My solution was to add a /etc/hosts entry for api.flickr.com and that way no DNS was being called. So far am on photo pull 1300 and no errors!

**Comment by yakneens** [comment]
Migrated your tip to wiki https://github.com/llevar/flickr_to_google_photos_migration/wiki
